# Data
path: /home/omarabdelgawad/my_workspace/Projects/Sharja/data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [8, 2]  # [number of keypoints, number of dim]
flip_idx: [0, 1, 2, 3, 4, 5, 6, 7]

# Classes
names:
  0: sperm